name = "r2-attempt-2"
main = "src/worker.ts"
compatibility_date = "2023-05-18"

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/r2/api/workers/workers-api-usage/
[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "shane-bucket"
preview_bucket_name = "fake-shane"

[[rules]]
type = "Data"
globs = ["**/jacob.png"]
fallthrough = true
